logo: https://raw.githubusercontent.com/osanseviero/hackerllama/gh-pages/hackerllama.jpg
title: Omar Sanseviero
google_analytics: G-SF72633X8L
remote_theme: jekyll-theme-minimal

plugins: 
  - jekyll-remote-theme