# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hackerllama',
                'doc_host': 'https://osanseviero.github.io',
                'git_url': 'https://github.com/osanseviero/hackerllama',
                'lib_path': 'hackerllama'},
  'syms': {'hackerllama.core': {'hackerllama.core.foo': ('core.html#foo', 'hackerllama/core.py')}}}
